[project]
name = "project"
version = "0.1.0"
description = "Prediction Project Week 5"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.120.0",
    "ipython>=9.6.0",
    "requests>=2.32.5",
    "scikit-learn==1.6.1",
    "uvicorn>=0.38.0",
]
